spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.204.150:8848
  application:
    name: blog-module

  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.huyu.mybatis.entity

