spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.204.150:8848
  application:
    name: authorization-module
  redis:
    database: 0
    host: 192.168.204.150
    port: 6379
    connect-timeout: 5000
    password: 123456