spring:
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.204.150:8848
    gateway:
      routes:
#        - id: blog-module
#          uri: lb:http://blog-module
#          predicates:
#            - Path=/api/blog/**
#          filters:
#            - RewritePath=/api/(?<segment>/?.*),/$\{segment}
#
#        - id: authentication-module
#          uri: lb:http://authentication-module
#          predicates:
#            - Path=/api/authentication/login/**
#            - Path=/api/authentication/register/**
#          filters:
#            - RewritePath=/api/(?<segment>/?.*),/$\{segment}


  application:
    name: gateway-module

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.gateway: TRACE